# Generated by Django 5.2.15 on 2026-07-07 14:16

from django.db import migrations, models


def backfill_slugs(apps, schema_editor):
    from slugify import slugify

    Quiz = apps.get_model("quizzes", "Quiz")
    used = set()
    for quiz in Quiz.objects.all().order_by("pk"):
        base = slugify(quiz.title) or quiz.language
        slug = base
        counter = 2
        while slug in used or Quiz.objects.filter(slug=slug).exclude(pk=quiz.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        used.add(slug)
        quiz.slug = slug
        quiz.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=280),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
