# Generated by Django 5.2.15 on 2026-07-07 14:16

from django.db import migrations, models


def backfill_slugs(apps, schema_editor):
    from slugify import slugify

    Lesson = apps.get_model("content", "Lesson")
    used = set()
    for lesson in Lesson.objects.all().order_by("pk"):
        base = slugify(lesson.title) or lesson.language
        slug = base
        counter = 2
        while slug in used or Lesson.objects.filter(slug=slug).exclude(pk=lesson.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        used.add(slug)
        lesson.slug = slug
        lesson.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        # 1. add the column without a uniqueness constraint
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=280),
        ),
        # 2. give every existing row a unique slug
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # 3. enforce uniqueness now that no duplicates remain
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
